<?php

use Phinx\Migration\AbstractMigration;
use Phinx\Db\Adapter\MysqlAdapter;

class Init extends AbstractMigration
{
    public function change()
    {
        $this->execute("ALTER DATABASE CHARACTER SET 'utf8';");
        $this->execute("ALTER DATABASE COLLATE='utf8_unicode_ci';");
        $table = $this->table("address", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('wavetrophy_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('road_group_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'wavetrophy_hash']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'road_group_hash']);
        $table->addColumn('city', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'name']);
        $table->addColumn('street', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'city']);
        $table->addColumn('zipcode', 'string', ['null' => false, 'limit' => 10, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'street']);
        $table->addColumn('coordinate_lat', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "The table for addresses", 'after' => 'zipcode']);
        $table->addColumn('coordinate_lon', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'coordinate_lat']);
        $table->addColumn('map_url_android', 'string', ['null' => false, 'limit' => 1000, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'coordinate_lon']);
        $table->addColumn('map_url_ios', 'string', ['null' => false, 'limit' => 1000, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'map_url_android']);
        $table->addColumn('description', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'map_url_ios']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'description']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->addColumn('comment', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "Comment about the location for the drivers", 'after' => 'archived_by']);
        $table->save();
        $table = $this->table("address_image", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('image_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to image.hash", 'after' => 'id']);
        $table->addColumn('address_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to address.hash", 'after' => 'image_hash']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'address_hash']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("car", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('reach', 'decimal', ['null' => false, 'precision' => 5, 'scale' => 2, 'after' => 'name']);
        $table->addColumn('power_supply', 'string', ['null' => true, 'default' => "AC", 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "Either AC or DC charging", 'after' => 'reach']);
        $table->addColumn('battery_size', 'decimal', ['null' => true, 'precision' => 5, 'scale' => 2, 'comment' => "The size of the battery in KW", 'after' => 'power_supply']);
        $table->addColumn('power_supply_min', 'decimal', ['null' => true, 'precision' => 5, 'scale' => 2, 'comment' => "The minimum charging rate in KW (eg 3,6)", 'after' => 'battery_size']);
        $table->addColumn('power_supply_max', 'decimal', ['null' => true, 'precision' => 5, 'scale' => 2, 'comment' => "The maximum charging ratein KW (eg. 22)", 'after' => 'power_supply_min']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'power_supply_max']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("contact", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('position', 'string', ['null' => false, 'limit' => 30, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('phonenumber', 'string', ['null' => false, 'limit' => 15, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'position']);
        $table->addColumn('first_name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'phonenumber']);
        $table->addColumn('last_name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'first_name']);
        $table->addColumn('email', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'last_name']);
        $table->addColumn('wavetrohpy_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference wavetrophy.hash", 'after' => 'email']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'wavetrohpy_hash']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("event", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('group_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to group.hash", 'after' => 'hash']);
        $table->addColumn('address_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'group_hash']);
        $table->addColumn('title', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'address_hash']);
        $table->addColumn('description', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'title']);
        $table->addColumn('start', 'datetime', ['null' => false, 'after' => 'description']);
        $table->addColumn('end', 'datetime', ['null' => false, 'after' => 'start']);
        $table->addColumn('day', 'string', ['null' => false, 'limit' => 5, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "Day is the day of the wave trophy event", 'after' => 'end']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'day']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("event_image", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('event_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to event.image", 'after' => 'id']);
        $table->addColumn('image_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to image.hash", 'after' => 'event_hash']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'image_hash']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("image", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('url', 'string', ['null' => false, 'limit' => 1000, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'url']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'name']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("permission", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable', 'comment' => "the table for the permissions"]);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('level', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'name']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'level']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("road_group", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('wavetrophy_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to wavetrohpy.hash", 'after' => 'hash']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'wavetrophy_hash']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'name']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_at']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_by']);
        $table->save();
        $table = $this->table("team", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('group_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to group.hash", 'after' => 'hash']);
        $table->addColumn('car_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to car.hash", 'after' => 'group_hash']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'car_hash']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'name']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("user", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10]);
        $table->addColumn('permission_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to permission.hash", 'after' => 'id']);
        $table->addColumn('team_hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "reference to team.hash", 'after' => 'permission_hash']);
        $table->addColumn('username', 'string', ['null' => false, 'limit' => 50, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'team_hash']);
        $table->addColumn('first_name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'username']);
        $table->addColumn('password', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'first_name']);
        $table->addColumn('language', 'string', ['null' => false, 'default' => "de_CH", 'limit' => 5, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'password']);
        $table->addColumn('email', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'language']);
        $table->addColumn('last_name', 'string', ['null' => true, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'email']);
        $table->addColumn('is_public', 'integer', ['null' => true, 'default' => "0", 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'comment' => "Indicates if this contact should be shown in all contacts in the app", 'after' => 'last_name']);
        $table->addColumn('mobile_number', 'string', ['null' => true, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "MUST be required if user is public", 'after' => 'is_public']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'mobile_number']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("wavetrophy", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_unicode_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('country', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'name']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'country']);
        $table->addColumn('created_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'string', ['null' => true, 'limit' => 80, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'archived_at']);
        $table->save();
    }
}
